In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
data = pd.read_csv('/Users/a1/ME583/sensor/data/sensor_readings_24.csv',header = None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.438,0.498,3.625,3.645,5.0,2.918,5.0,2.351,2.332,2.643,...,0.593,0.502,0.493,0.504,0.445,0.431,0.444,0.440,0.429,Slight-Right-Turn
1,0.438,0.498,3.625,3.648,5.0,2.918,5.0,2.637,2.332,2.649,...,0.592,0.502,0.493,0.504,0.449,0.431,0.444,0.443,0.429,Slight-Right-Turn
2,0.438,0.498,3.625,3.629,5.0,2.918,5.0,2.637,2.334,2.643,...,0.593,0.502,0.493,0.504,0.449,0.431,0.444,0.446,0.429,Slight-Right-Turn
3,0.437,0.501,3.625,3.626,5.0,2.918,5.0,2.353,2.334,2.642,...,0.593,0.502,0.493,0.504,0.449,0.431,0.444,0.444,0.429,Slight-Right-Turn
4,0.438,0.498,3.626,3.629,5.0,2.918,5.0,2.640,2.334,2.639,...,0.592,0.502,0.493,0.504,0.449,0.431,0.444,0.441,0.429,Slight-Right-Turn

In [3]:
data = data.replace('Move-Forward',1)
data = data.replace('Slight-Right-Turn',2)
data = data.replace('Slight-Left-Turn',3)
data = data.replace('Sharp-Right-Turn',4)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.438,0.498,3.625,3.645,5.0,2.918,5.0,2.351,2.332,2.643,...,0.593,0.502,0.493,0.504,0.445,0.431,0.444,0.440,0.429,2
1,0.438,0.498,3.625,3.648,5.0,2.918,5.0,2.637,2.332,2.649,...,0.592,0.502,0.493,0.504,0.449,0.431,0.444,0.443,0.429,2
2,0.438,0.498,3.625,3.629,5.0,2.918,5.0,2.637,2.334,2.643,...,0.593,0.502,0.493,0.504,0.449,0.431,0.444,0.446,0.429,2
3,0.437,0.501,3.625,3.626,5.0,2.918,5.0,2.353,2.334,2.642,...,0.593,0.502,0.493,0.504,0.449,0.431,0.444,0.444,0.429,2
4,0.438,0.498,3.626,3.629,5.0,2.918,5.0,2.640,2.334,2.639,...,0.592,0.502,0.493,0.504,0.449,0.431,0.444,0.441,0.429,2

In [4]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2)

In [5]:
xtrain = train.iloc[:, 0:24].values
ytrain = train.iloc[: , -1].values
xtest  = test.iloc[:, 0:24].values
ytest  = test.iloc[:,-1].values

In [6]:
from sklearn.svm import SVC
classifier24 = SVC(kernel='rbf', random_state = 1)
classifier24.fit(xtrain,ytrain)

SVC(random_state=1)

In [7]:
y_pred_test = classifier24.predict(xtest)
y_pred_train = classifier24.predict(xtrain)

from sklearn import metrics
acc1 = metrics.accuracy_score(ytest,y_pred_test)
acc = metrics.accuracy_score(ytrain,y_pred_train)

print ("Accuracy for train set:"),
print (acc)
print ("Accuracy for test set:"),
print (acc1)

Accuracy for train set:
0.9106324472960586
Accuracy for test set:
0.8818681318681318

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,y_pred_test)
accuracy = float(cm.diagonal().sum())/len(ytest)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy)

Accuracy Of SVM For The Given Dataset :  0.8818681318681318

In [9]:
from sklearn.naive_bayes import GaussianNB
clf24 = GaussianNB()
clf24.fit(xtrain, ytrain)

GaussianNB()

In [10]:
y_pred_test_gnb = clf24.predict(xtest)
y_pred_train_gnb = clf24.predict(xtrain)

from sklearn import metrics
acc1 = metrics.accuracy_score(ytest,y_pred_test_gnb)
acc = metrics.accuracy_score(ytrain,y_pred_train_gnb)

print ("Accuracy for train set:"),
print (acc)
print ("Accuracy for test set:"),
print (acc1)

Accuracy for train set:
0.5341429880843263
Accuracy for test set:
0.5302197802197802

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,y_pred_test_gnb)
accuracy = float(cm.diagonal().sum())/len(ytest)
print("\nAccuracy Of Gaussian For The Given Dataset : ", accuracy)

Accuracy Of Gaussian For The Given Dataset :  0.5302197802197802